# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      MongoURI:
        description: MongoURI
        default: ''
        required: true
      MYSQL_USER_HOST:
        description: MYSQL_USER_HOST
        default: ''
        required: true
      MYSQL_PASSWORD:
        description: MYSQL_PASSWORD
        default: ''
        required: true
      MYSQL_BILLING_HOST:
        description: MYSQL_BILLING_HOST
        default: ''
        required: true
      MYSQL_NOTIFICATION_HOST:
        description: MYSQL_NOTIFICATION_HOST
        default: ''
        required: true
      
      
jobs:
  dbMigration:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Setup latest NPM
      run: npm install -g npm@latest
    - name: Setup dependencies
      run: npm install
    - name: run node script
      run: node index.js ${{inputs.MongoURI}} ${{inputs.MYSQL_USER_HOST}} ${{inputs.MYSQL_PASSWORD}} ${{inputs.MYSQL_BILLING_HOST}} ${{inputs.MYSQL_NOTIFICATION_HOST}}
