# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: environment
        default: ''
        required: true 
        type: choice
        options:
          - TEST_CMS_3
          - TEST_CMS_2
          - DEV_FUSION
      name:
        description: name
        default: ''
        required: true
      
      
jobs:
  dbMigration:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Setup latest NPM
      run: npm install -g npm@latest
    - name: Setup dependencies
      run: npm install
    - name: run node script
      run: node index.js ${{inputs.environment}} ${{inputs.cpName}}
